version: '3.7'

services:

  angular:
    container_name: 'cheatcodes-angular'
    image: 'cheatcodes-angular'
    build:
      context: ./CheatCodes.UI/
      dockerfile: nginx.prod.dockerfile
    ports:
     - "4200:80"
    depends_on:
     - "sts"
     - "api"
    networks:
     - cheatcodes-network

  api:
    container_name: 'cheatcodes-api'
    image: 'cheatcodes-api'
    build:
      context: .
      dockerfile: ./Api/api.dockerfile
    ports:
     - "44326:80"
    depends_on:
     - "sts"
    networks:
      - cheatcodes-network

  sts:
    container_name: 'cheatcodes-sts'
    image: 'cheatcodes-sts'
    build:
      context: .
      dockerfile: ./STS/IdSNet/sts.dockerfile
    ports:
     - "5002:80"
    networks:
      - cheatcodes-network

networks:
  cheatcodes-network:
    driver: bridge
