version: '3.7'

services:

  api:
    container_name: 'cheatcodes-api'
    image: 'cheatcodes-api'
    build:
      context: .
      dockerfile: ./Api/api.dockerfile
    ports:
     - "44326:80"
    depends_on:
     - "sts"
    networks:
      - cheatcodes-network

  sts:
    container_name: 'cheatcodes-sts'
    image: 'cheatcodes-sts'
    build:
      context: .
      dockerfile: ./STS/IdSNet/sts.dockerfile
    ports:
     - "5002:5002"
    networks:
      - cheatcodes-network

networks:
  cheatcodes-network:
    driver: bridge
