//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
//<auto-generated>
//  This code was generated by a tool
//  Runtime Version: 4.0.30319.42000
//
//  Changes to this file may cause incorrect behavior and will be lost if
//  the code is regenerated.
//</auto-generated>
//- - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
using System;
using System.CodeDom.Compiler;

namespace Api.Test.Framework.Builders
{

    [GeneratedCode("Builders", "1.0")]
    public partial class CategoryBuilder : Builder<Domain.Category>
    {
        private Lazy<System.Collections.Generic.IList<Domain.CategoryField>> _categoryFields = new Lazy<System.Collections.Generic.IList<Domain.CategoryField>>(default(System.Collections.Generic.IList<Domain.CategoryField>));
        private Lazy<System.Collections.Generic.IList<Domain.Category>> _childCategories = new Lazy<System.Collections.Generic.IList<Domain.Category>>(default(System.Collections.Generic.IList<Domain.Category>));
        private Lazy<System.String> _description = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _id = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.String> _name = new Lazy<System.String>(default(System.String));
        private Lazy<Domain.Category> _parentCategory = new Lazy<Domain.Category>(default(Domain.Category));

        [GeneratedCode("ModelBuilders", "1.0")]
        public override Domain.Category Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Domain.Category>(new Domain.Category
                {
                    CategoryFields = _categoryFields.Value,
                    ChildCategories = _childCategories.Value,
                    Description = _description.Value,
                    Id = _id.Value,
                    Name = _name.Value,
                    ParentCategory = _parentCategory.Value,
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static CategoryBuilder Default()
        {
            return new CategoryBuilder();
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithCategoryFields(System.Collections.Generic.IList<Domain.CategoryField> value)
        {
            return WithCategoryFields(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithCategoryFields(Func<System.Collections.Generic.IList<Domain.CategoryField>> func)
        {
            _categoryFields = new Lazy<System.Collections.Generic.IList<Domain.CategoryField>>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutCategoryFields()
        {
            _categoryFields = new Lazy<System.Collections.Generic.IList<Domain.CategoryField>>(default(System.Collections.Generic.IList<Domain.CategoryField>));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithChildCategories(System.Collections.Generic.IList<Domain.Category> value)
        {
            return WithChildCategories(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithChildCategories(Func<System.Collections.Generic.IList<Domain.Category>> func)
        {
            _childCategories = new Lazy<System.Collections.Generic.IList<Domain.Category>>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutChildCategories()
        {
            _childCategories = new Lazy<System.Collections.Generic.IList<Domain.Category>>(default(System.Collections.Generic.IList<Domain.Category>));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithDescription(System.String value)
        {
            return WithDescription(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithDescription(Func<System.String> func)
        {
            _description = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutDescription()
        {
            _description = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithId(System.Int32 value)
        {
            return WithId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithId(Func<System.Int32> func)
        {
            _id = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutId()
        {
            _id = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithName(System.String value)
        {
            return WithName(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithName(Func<System.String> func)
        {
            _name = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutName()
        {
            _name = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithParentCategory(Domain.Category value)
        {
            return WithParentCategory(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithParentCategory(Func<Domain.Category> func)
        {
            _parentCategory = new Lazy<Domain.Category>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public CategoryBuilder WithoutParentCategory()
        {
            _parentCategory = new Lazy<Domain.Category>(default(Domain.Category));
            return this;
        }

    }

    [GeneratedCode("Builders", "1.0")]
    public partial class FieldBuilder : Builder<Domain.Field>
    {
        private Lazy<System.String> _description = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _id = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.String> _name = new Lazy<System.String>(default(System.String));

        [GeneratedCode("ModelBuilders", "1.0")]
        public override Domain.Field Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Domain.Field>(new Domain.Field
                {
                    Description = _description.Value,
                    Id = _id.Value,
                    Name = _name.Value,
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static FieldBuilder Default()
        {
            return new FieldBuilder();
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithDescription(System.String value)
        {
            return WithDescription(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithDescription(Func<System.String> func)
        {
            _description = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithoutDescription()
        {
            _description = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithId(System.Int32 value)
        {
            return WithId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithId(Func<System.Int32> func)
        {
            _id = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithoutId()
        {
            _id = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithName(System.String value)
        {
            return WithName(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithName(Func<System.String> func)
        {
            _name = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public FieldBuilder WithoutName()
        {
            _name = new Lazy<System.String>(default(System.String));
            return this;
        }

    }

    [GeneratedCode("Builders", "1.0")]
    public partial class ItemBuilder : Builder<Domain.Item>
    {
        private Lazy<System.String> _description = new Lazy<System.String>(default(System.String));
        private Lazy<System.Int32> _id = new Lazy<System.Int32>(default(System.Int32));
        private Lazy<System.String> _name = new Lazy<System.String>(default(System.String));

        [GeneratedCode("ModelBuilders", "1.0")]
        public override Domain.Item Build()
        {
            if (Object?.IsValueCreated != true)
            {
                Object = new Lazy<Domain.Item>(new Domain.Item
                {
                    Description = _description.Value,
                    Id = _id.Value,
                    Name = _name.Value,
                });
            }

            PostBuild(Object.Value);

            return Object.Value;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public static ItemBuilder Default()
        {
            return new ItemBuilder();
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithDescription(System.String value)
        {
            return WithDescription(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithDescription(Func<System.String> func)
        {
            _description = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutDescription()
        {
            _description = new Lazy<System.String>(default(System.String));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithId(System.Int32 value)
        {
            return WithId(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithId(Func<System.Int32> func)
        {
            _id = new Lazy<System.Int32>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutId()
        {
            _id = new Lazy<System.Int32>(default(System.Int32));
            return this;
        }
        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithName(System.String value)
        {
            return WithName(() => value);
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithName(Func<System.String> func)
        {
            _name = new Lazy<System.String>(func);
            return this;
        }

        [GeneratedCode("ModelBuilders", "1.0")]
        public ItemBuilder WithoutName()
        {
            _name = new Lazy<System.String>(default(System.String));
            return this;
        }

    }

}
